In [2]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Marks": [78, 92, 65, 88]
}

df = pd.DataFrame(data)

In [3]:
# Q6
# Sort students by marks ascending.

df.sort_values('Marks', ascending=False)

   Name  Marks
1  Sara     92
3  Emma     88
0   Ali     78
2  John     65

In [4]:
# Q7
# Sort descending.

df.sort_values('Marks')

   Name  Marks
2  John     65
0   Ali     78
3  Emma     88
1  Sara     92