CSV file read student_dataset.csv
Columns: name, marks
Average marks nikaalo
Max & Min marks
Topper ka naam print karo

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('student_dataset.csv')
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Grade,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,B+,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,C,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,D,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,B+,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,B+,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,D,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [4]:
# df['Marks'] = df['Math'] + df['Physics'] + df['Chemistry']

In [5]:
df.insert(5, "Marks", df['Math'] + df['Physics'] + df['Chemistry'])
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Marks,Grade,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,214,B+,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,244,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,182,C,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,142,D,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,238,B+,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,192,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,215,B+,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,166,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,178,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,125,D,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [6]:
avg_marks = df['Marks'].mean()
max_mark = df['Marks'].max()
min_marks = df['Marks'].min()
topper = df.loc[df['Marks'].idxmax(), 'Student_Names']
lowest = df.loc[df['Marks'].idxmin(), 'Student_Names']

In [7]:
print('Average Marks:', avg_marks)
print('Maximum Marks:', max_mark)
print('Minimum Marks:', min_marks)
print('Topper Name:', topper, max_mark)
print('Lowest Name:', lowest, min_marks)
# print(topper1)

Average Marks: 164.82855555555557
Maximum Marks: 291
Minimum Marks: 33
Topper Name: Eric Baker 291
Lowest Name: Jill Jones 33