🎓 Student Result Analyzer
Dataset:

name, maths, physics, chemistry


Tasks:

Total marks

Percentage

Grade system

p >= 90:
"A+"
p >= 75:
"A"
p >= 60:
"B"
p >= 40:
"C"
else:
"Fail"

Topper

Subject-wise average

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('student_dataset.csv')
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Grade,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,B+,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,C,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,D,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,B+,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,B+,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,D,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [28]:
df.insert(5, 'Total_marks', df['Math'] + df['Physics'] + df['Chemistry'])
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Total_marks,Grade,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,214,B+,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,244,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,182,C,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,142,D,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,238,B+,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,192,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,215,B+,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,166,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,178,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,125,D,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [29]:
df.insert(6, 'Percentage', (df['Total_marks']/300)*100)
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Total_marks,Percentage,Grade,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,214,71.333333,B+,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,244,81.333333,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,182,60.666667,C,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,142,47.333333,D,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,238,79.333333,B+,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,192,64.000000,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,215,71.666667,B+,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,166,55.333333,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,178,59.333333,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,125,41.666667,D,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [30]:
def grade(a):
    if a>=90:
        return "A+"
    elif a>=75:
        return "A"
    elif a>=60:
        return "B"
    elif a>=40:
        return "C"
    else:
        return "Fail"

In [31]:
df.insert(8, "Grade1", df['Percentage'].apply(grade))
df

,Student_Names,Phone_No.,Math,Physics,Chemistry,Total_marks,Percentage,Grade,Grade1,Comment,Roll No.,School Name,Student Address
0,Donald Contreras,9208625450,76,84,54,214,71.333333,B+,B,Good Pursuance,524613,Martin Luther School,"478 Mooney Park, New Valerie, VI 28836"
1,Joseph Horton,9886408555,91,75,78,244,81.333333,A,A,Very Good Achivement,561635,Martin Luther School,"037 Matthew Shores, Greeneton, CA 98399"
2,Savannah Burns MD,9047592659,64,98,20,182,60.666667,C,B,Below Average Achivement,560985,Martin Luther School,"96124 Lloyd Streets, Edwardmouth, DC 61677"
3,William Carter,9048473864,15,95,32,142,47.333333,D,C,Poor Pursuance,535126,Martin Luther School,"11959 Clark Village, Ivanview, NH 43940"
4,John Rodriguez,9685225730,86,86,66,238,79.333333,B+,A,Good Pursuance,559410,Martin Luther School,"051 Weaver Glen Apt. 724, West Davidborough, M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,Kimberly Stevens,9129352703,40,87,65,192,64.000000,B,B,Average Performance,569342,Martin Luther School,"27054 Adrian Streets, Diazmouth, OH 81346"
8996,Kelsey Bonilla,9649715711,56,84,75,215,71.666667,B+,B,Good Pursuance,530124,Martin Luther School,"570 Christopher Run, Williammouth, ND 11535"
8997,Kelly Dunn,9825362271,80,70,16,166,55.333333,C,C,Below Average Achivement,592266,Martin Luther School,"32283 Carpenter Summit, North Patricia, PR 51483"
8998,Joseph Nichols,9363540473,24,95,59,178,59.333333,C,C,Below Average Achivement,583028,Martin Luther School,"2336 Blackburn Fall Apt. 905, South Shelby, ND..."
8999,Susan Armstrong,9879539785,31,76,18,125,41.666667,D,C,Poor Pursuance,503637,Martin Luther School,"2328 Jennifer Extension, Lake David, OR 11243"

In [33]:
topper = df.loc[df['Percentage'].idxmax(), 'Student_Names']
topper

'Eric Baker'

In [41]:
physics_avg = df['Physics'].mean()
print("Physics Average:", physics_avg)

math_avg = df['Math'].mean()
print("Math Average:", math_avg)

chemistry_avg = df['Chemistry'].mean()
print("Chemistry Average:", round(chemistry_avg, 2))

Physics Average: 54.69755555555555
Math Average: 55.27611111111111
Chemistry Average: 54.85