movies.csv (name, genre, rating)
Tasks:

Genre-wise average rating

Har genre ka best movie

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies1.csv")
df

           name    genre  rating
0     Inception   Sci-Fi     8.8
1  Interstellar   Sci-Fi     8.6
2           KGF   Action     8.4
3           RRR   Action     8.6
4       Titanic  Romance     7.9
5      Notebook  Romance     7.8
6   Oppenheimer    Drama     9.0
7  Forrest Gump    Drama     8.8

In [7]:
df.groupby(by="genre")['rating'].mean()

genre
Action     8.50
Drama      8.90
Romance    7.85
Sci-Fi     8.70
Name: rating, dtype: float64

In [9]:
df.loc[df.groupby(by="genre")['rating'].idxmax()]

          name    genre  rating
3          RRR   Action     8.6
6  Oppenheimer    Drama     9.0
4      Titanic  Romance     7.9
0    Inception   Sci-Fi     8.8