attendance.csv (name, attendance%)

Task: Attendance ko 3 buckets me baantna

High → > 85

Medium → 70–85

Low → < 70

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('attendance.csv')
df

    name  attendance_percentage
0   Aman                     82
1   Riya                     68
2   Shiv                     74
3   Neha                     90
4  Arjun                     60
5  Karan                     88

In [9]:
def att_category(x):
    if x>85:
        return "High"
    elif 70 <= x <= 85:
        return "Medium"
    else:
        return "Low"

In [11]:

df['Category'] = df['attendance_percentage'].apply(att_category)
df

    name  attendance_percentage Category
0   Aman                     82   Medium
1   Riya                     68      Low
2   Shiv                     74   Medium
3   Neha                     90     High
4  Arjun                     60      Low
5  Karan                     88     High

In [13]:
df['Category'].value_counts()

Category
Medium    2
Low       2
High      2
Name: count, dtype: int64