bank.csv (customer, balance)
Tasks:

Richest customer

Balance below average waale customers

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('bank.csv')
df

  customer  balance
0     Aman    45000
1     Riya    72000
2     Shiv    30000
3     Neha    90000
4    Arjun    38000
5    Karan    60000

In [13]:
df.loc[df['balance'].idxmax()]

customer     Neha
balance     90000
Name: 3, dtype: object

In [14]:
avg_balance = np.mean(df['balance'])
avg_balance

np.float64(55833.333333333336)

In [15]:
df[df['balance']<avg_balance]

  customer  balance
0     Aman    45000
2     Shiv    30000
4    Arjun    38000

In [16]:
df[df["balance"].idxmax()]

KeyError: 3