Questions

Load this CSV into Pandas.

Display first and last 3 rows.

Check data types and memory usage.

Create a new column total_amount = price * quantity.

Find:

Total revenue

Average order value

List unique cities and payment modes.

Sort orders by total_amount descending.

Filter all Electronics orders above ₹10,000.

Rename columns to snake_case.

Convert order_date to datetime and extract day, month.

In [42]:
import numpy as np
import pandas as pd

In [43]:
df = pd.read_csv('sales_transactions.csv')
# Display first 3 rows
df.head(3)

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode
0,101,2025-01-01,C001,Phone,Electronics,15000,1,Delhi,UPI
1,102,2025-01-01,C002,Laptop,Electronics,55000,1,Mumbai,Credit Card
2,103,2025-01-02,C001,Headphones,Accessories,2000,2,Delhi,UPI

In [44]:
# Display last 3 rows
df.tail(3)

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode
2,103,2025-01-02,C001,Headphones,Accessories,2000,2,Delhi,UPI
3,104,2025-01-03,C003,Chair,Furniture,3000,1,Bangalore,Debit Card
4,105,2025-01-03,C004,Desk,Furniture,7000,1,Delhi,UPI

Check data types and memory usage.

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      5 non-null      int64
 1   order_date    5 non-null      object
 2   customer_id   5 non-null      object
 3   product       5 non-null      object
 4   category      5 non-null      object
 5   price         5 non-null      int64
 6   quantity      5 non-null      int64
 7   city          5 non-null      object
 8   payment_mode  5 non-null      object
dtypes: int64(3), object(6)
memory usage: 492.0+ bytes

Create a new column total_amount = price * quantity.

In [46]:
df['total_amount'] = df['price'] * df['quantity']
df

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode,total_amount
0,101,2025-01-01,C001,Phone,Electronics,15000,1,Delhi,UPI,15000
1,102,2025-01-01,C002,Laptop,Electronics,55000,1,Mumbai,Credit Card,55000
2,103,2025-01-02,C001,Headphones,Accessories,2000,2,Delhi,UPI,4000
3,104,2025-01-03,C003,Chair,Furniture,3000,1,Bangalore,Debit Card,3000
4,105,2025-01-03,C004,Desk,Furniture,7000,1,Delhi,UPI,7000

In [47]:
total_revenue = df['total_amount'].sum()
total_revenue

np.int64(84000)

In [48]:
avg_order_val = df['total_amount'].mean()
avg_order_val

np.float64(16800.0)

In [49]:
# List unique cities and payment modes.
df['city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [50]:
df['payment_mode'].unique()

array(['UPI', 'Credit Card', 'Debit Card'], dtype=object)

In [51]:
# Sort orders by total_amount descending.
df.sort_values(by='total_amount', ascending=False)

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode,total_amount
1,102,2025-01-01,C002,Laptop,Electronics,55000,1,Mumbai,Credit Card,55000
0,101,2025-01-01,C001,Phone,Electronics,15000,1,Delhi,UPI,15000
4,105,2025-01-03,C004,Desk,Furniture,7000,1,Delhi,UPI,7000
2,103,2025-01-02,C001,Headphones,Accessories,2000,2,Delhi,UPI,4000
3,104,2025-01-03,C003,Chair,Furniture,3000,1,Bangalore,Debit Card,3000

In [52]:
# Filter all Electronics orders above ₹10,000.
df[(df['category']== 'Electronics') & (df['total_amount']>10000)]

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode,total_amount
0,101,2025-01-01,C001,Phone,Electronics,15000,1,Delhi,UPI,15000
1,102,2025-01-01,C002,Laptop,Electronics,55000,1,Mumbai,Credit Card,55000

In [53]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [55]:
date_time = pd.to_datetime(df['order_date'])
date_time.dt.day

0    1
1    1
2    2
3    3
4    3
Name: order_date, dtype: int32

In [56]:
date_time.dt.month

0    1
1    1
2    1
3    1
4    1
Name: order_date, dtype: int32

In [58]:
df["order_date"] = pd.to_datetime(df["order_date"])

df["order_day"] = df["order_date"].dt.day
df["order_month"] = df["order_date"].dt.month

In [60]:
df.head()

,order_id,order_date,customer_id,product,category,price,quantity,city,payment_mode,total_amount,order_day,order_month
0,101,2025-01-01,C001,Phone,Electronics,15000,1,Delhi,UPI,15000,1,1
1,102,2025-01-01,C002,Laptop,Electronics,55000,1,Mumbai,Credit Card,55000,1,1
2,103,2025-01-02,C001,Headphones,Accessories,2000,2,Delhi,UPI,4000,2,1
3,104,2025-01-03,C003,Chair,Furniture,3000,1,Bangalore,Debit Card,3000,3,1
4,105,2025-01-03,C004,Desk,Furniture,7000,1,Delhi,UPI,7000,3,1