Ek DataFrame banao manually:

Name   Age   Salary

A      22    25000

B      25    40000

C      21    18000


Salary ka NumPy array banao

Mean salary

Highest salary

Salary > 20000 waale employees

In [1]:
import numpy as np
import pandas as pd

In [2]:
Data = {
    "Name": ['A', 'B', 'C'],
    "Age": [22, 25 , 21],
    "Salary": [25000, 40000, 18000]
}

In [3]:
df = pd.DataFrame(Data)
df

  Name  Age  Salary
0    A   22   25000
1    B   25   40000
2    C   21   18000

In [4]:
Salary_array = np.array(df['Salary'])
Salary_array
# print("Array of Salary:", Salary_array)

array([25000, 40000, 18000])

In [5]:
Mean_Salary = df['Salary'].mean()
High_Salaray = df['Salary'].max()
print(Mean_Salary)
print(High_Salaray)

27666.666666666668
40000

In [6]:
df[df['Salary'] > 20000]

  Name  Age  Salary
0    A   22   25000
1    B   25   40000