Questions

Load the dataset using Pandas.

Check data types and memory usage (optimize if needed).

Convert joining_date to datetime.

Using NumPy, calculate:

mean salary

median salary

salary standard deviation

Find employees:

earning above average salary

with experience > 5 years

Add a new column salary_bucket:

Low (<40k)

Medium (40k–80k)

High (>80k)

Replace missing salaries using NumPy mean (not Pandas shortcut).

In [132]:
import numpy as np
import pandas as pd

In [133]:
df = pd.read_csv('employees1.csv')
df

,employee_id,name,age,department,salary,experience_years,joining_date
0,101,Amit,28,IT,55000.0,4,2021-06-15
1,102,Riya,34,HR,48000.0,8,2018-03-10
2,103,Kunal,26,Marketing,42000.0,2,2022-01-05
3,104,Neha,41,Finance,92000.0,15,2010-11-20
4,105,Rahul,38,IT,78000.0,12,2013-07-01
5,106,Pooja,30,Sales,NaN,6,2019-09-18
6,107,Arjun,25,IT,36000.0,1,2023-02-12
7,108,Simran,45,Finance,110000.0,20,2005-05-30

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   employee_id       8 non-null      int64
 1   name              8 non-null      object
 2   age               8 non-null      int64
 3   department        8 non-null      object
 4   salary            7 non-null      float64
 5   experience_years  8 non-null      int64
 6   joining_date      8 non-null      object
dtypes: float64(1), int64(3), object(3)
memory usage: 580.0+ bytes

In [135]:
pd.to_datetime(df['joining_date'])

0   2021-06-15
1   2018-03-10
2   2022-01-05
3   2010-11-20
4   2013-07-01
5   2019-09-18
6   2023-02-12
7   2005-05-30
Name: joining_date, dtype: datetime64[ns]

In [136]:
np.mean(df['salary'])

np.float64(65857.14285714286)

In [137]:
np.median(df['salary'])

np.float64(nan)

In [138]:
np.std(df['salary'])

25848.064704723867

In [139]:
df[(df['salary'] > df['salary'].mean())]

,employee_id,name,age,department,salary,experience_years,joining_date
3,104,Neha,41,Finance,92000.0,15,2010-11-20
4,105,Rahul,38,IT,78000.0,12,2013-07-01
7,108,Simran,45,Finance,110000.0,20,2005-05-30

In [140]:
df[df['experience_years'] > 5]

,employee_id,name,age,department,salary,experience_years,joining_date
1,102,Riya,34,HR,48000.0,8,2018-03-10
3,104,Neha,41,Finance,92000.0,15,2010-11-20
4,105,Rahul,38,IT,78000.0,12,2013-07-01
5,106,Pooja,30,Sales,NaN,6,2019-09-18
7,108,Simran,45,Finance,110000.0,20,2005-05-30

In [141]:
def bucket(x):
    if x < 40000:
        return "Low"
    elif 40000 <= x <= 80000:
        return "Medium"
    elif x > 80000:
        return "High"
    else:
        return "Missing value"

In [142]:
df['salary_bucket'] = df['salary'].apply(bucket)
df

,employee_id,name,age,department,salary,experience_years,joining_date,salary_bucket
0,101,Amit,28,IT,55000.0,4,2021-06-15,Medium
1,102,Riya,34,HR,48000.0,8,2018-03-10,Medium
2,103,Kunal,26,Marketing,42000.0,2,2022-01-05,Medium
3,104,Neha,41,Finance,92000.0,15,2010-11-20,High
4,105,Rahul,38,IT,78000.0,12,2013-07-01,Medium
5,106,Pooja,30,Sales,NaN,6,2019-09-18,Missing value
6,107,Arjun,25,IT,36000.0,1,2023-02-12,Low
7,108,Simran,45,Finance,110000.0,20,2005-05-30,High

In [143]:
# df['salary'].fillna(df['salary'].mean(), inplace=True)
# df

In [144]:
df['salary'].replace(np.nan, np.mean(df['salary']))
df

,employee_id,name,age,department,salary,experience_years,joining_date,salary_bucket
0,101,Amit,28,IT,55000.0,4,2021-06-15,Medium
1,102,Riya,34,HR,48000.0,8,2018-03-10,Medium
2,103,Kunal,26,Marketing,42000.0,2,2022-01-05,Medium
3,104,Neha,41,Finance,92000.0,15,2010-11-20,High
4,105,Rahul,38,IT,78000.0,12,2013-07-01,Medium
5,106,Pooja,30,Sales,NaN,6,2019-09-18,Missing value
6,107,Arjun,25,IT,36000.0,1,2023-02-12,Low
7,108,Simran,45,Finance,110000.0,20,2005-05-30,High