Q1

Load CSV and:

Show first 10 rows

Show dataset shape

Show column names

Q2

Find:

Total number of orders

Total revenue (price * quantity)

Q3

Find:

Unique cities count

Unique product count

Q4

Filter:

Orders where city = "Delhi"

Orders where quantity > 3

Q5

Create new column:

total_amount = price * quantity

✅ NumPy Basic Practice
Q6

Create numpy array of product prices → find:

Mean

Median

Standard deviation

Q7

Generate random sales data (100 days)
Find:

Max sale day

Min sale day

In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv("orders1.csv")
df

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_mode
0,1001,C101,2025-01-02,T-Shirt,Clothing,599,2,Delhi,UPI
1,1002,C102,2025-01-03,Shoes,Footwear,2499,1,Mumbai,Card
2,1003,C103,2025-01-03,Jeans,Clothing,1799,1,Bangalore,UPI
3,1004,C101,2025-01-04,Watch,Accessories,3299,1,Delhi,COD
4,1005,C104,2025-01-05,Headphones,Electronics,1999,2,Pune,UPI
5,1006,C105,2025-01-06,T-Shirt,Clothing,599,3,Delhi,Card
6,1007,C106,2025-01-06,Laptop,Electronics,65000,1,Hyderabad,Card
7,1008,C102,2025-01-07,Shoes,Footwear,2499,2,Mumbai,UPI
8,1009,C107,2025-01-08,Backpack,Accessories,1299,1,Chennai,COD
9,1010,C108,2025-01-09,Mobile,Electronics,22000,1,Delhi,UPI

In [52]:
df.head(10)

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_mode
0,1001,C101,2025-01-02,T-Shirt,Clothing,599,2,Delhi,UPI
1,1002,C102,2025-01-03,Shoes,Footwear,2499,1,Mumbai,Card
2,1003,C103,2025-01-03,Jeans,Clothing,1799,1,Bangalore,UPI
3,1004,C101,2025-01-04,Watch,Accessories,3299,1,Delhi,COD
4,1005,C104,2025-01-05,Headphones,Electronics,1999,2,Pune,UPI
5,1006,C105,2025-01-06,T-Shirt,Clothing,599,3,Delhi,Card
6,1007,C106,2025-01-06,Laptop,Electronics,65000,1,Hyderabad,Card
7,1008,C102,2025-01-07,Shoes,Footwear,2499,2,Mumbai,UPI
8,1009,C107,2025-01-08,Backpack,Accessories,1299,1,Chennai,COD
9,1010,C108,2025-01-09,Mobile,Electronics,22000,1,Delhi,UPI

In [53]:
np.shape(df)
df.shape

(10, 9)

In [54]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'product', 'category', 'price',
       'quantity', 'city', 'payment_mode'],
      dtype='object')

In [55]:
df.shape[0]

10

In [56]:
total_revenue= df['price'] * df['quantity']
np.sum(total_revenue)

np.int64(107887)

In [57]:
df['city'].nunique()

6

In [58]:
df['product'].nunique()

8

In [59]:
df[(df['city']=="delhi") & (df['quantity']>3)]

Empty DataFrame
Columns: [order_id, customer_id, order_date, product, category, price, quantity, city, payment_mode]
Index: []

In [60]:
df['total_amount'] = df['price'] * df['quantity']
df

,order_id,customer_id,order_date,product,category,price,quantity,city,payment_mode,total_amount
0,1001,C101,2025-01-02,T-Shirt,Clothing,599,2,Delhi,UPI,1198
1,1002,C102,2025-01-03,Shoes,Footwear,2499,1,Mumbai,Card,2499
2,1003,C103,2025-01-03,Jeans,Clothing,1799,1,Bangalore,UPI,1799
3,1004,C101,2025-01-04,Watch,Accessories,3299,1,Delhi,COD,3299
4,1005,C104,2025-01-05,Headphones,Electronics,1999,2,Pune,UPI,3998
5,1006,C105,2025-01-06,T-Shirt,Clothing,599,3,Delhi,Card,1797
6,1007,C106,2025-01-06,Laptop,Electronics,65000,1,Hyderabad,Card,65000
7,1008,C102,2025-01-07,Shoes,Footwear,2499,2,Mumbai,UPI,4998
8,1009,C107,2025-01-08,Backpack,Accessories,1299,1,Chennai,COD,1299
9,1010,C108,2025-01-09,Mobile,Electronics,22000,1,Delhi,UPI,22000

In [61]:
arr = np.array(df['price'])
arr

array([  599,  2499,  1799,  3299,  1999,   599, 65000,  2499,  1299,
       22000])

In [62]:
np.mean(arr)

np.float64(10159.2)

In [63]:
np.median(arr)

np.float64(2249.0)

In [64]:
np.std(arr)

np.float64(19261.14576446583)

In [65]:
df["day"] = pd.to_datetime(df['order_date'])

In [70]:
df.loc[df['price'].idxmax()]

order_id                       1007
customer_id                    C106
order_date               2025-01-06
product                      Laptop
category                Electronics
price                         65000
quantity                          1
city                      Hyderabad
payment_mode                   Card
total_amount                  65000
day             2025-01-06 00:00:00
Name: 6, dtype: object

In [71]:
df.loc[df['price'].idxmin()]

order_id                       1001
customer_id                    C101
order_date               2025-01-02
product                     T-Shirt
category                   Clothing
price                           599
quantity                          2
city                          Delhi
payment_mode                    UPI
total_amount                   1198
day             2025-01-02 00:00:00
Name: 0, dtype: object