✅ Pandas Intermediate
Q8 — Grouping

Find:

Average salary per department

Max salary per department

Q9 — Sorting

Top 10 highest paid employees

Q10 — Conditional Analysis

Find:
Employees with:

Salary > company average

Experience > 5 AND Salary > 8 LPA

Q11 — Pivot Table (Very Important for Jobs)

Create Pivot:

Index → department  
Values → salary  
Agg → mean

Q12 — Missing Values

Handle dataset with missing salary:

Find null count

Replace with department average

✅ NumPy Intermediate
Q13

Create 2D array → monthly sales of 5 products for 12 months
Find:

Best selling product overall

Best month overall

Q14

Normalize salary data using NumPy formula

In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('employees2.csv')
df

  emp_id    name department     salary  experience_years        city
0   E101   Rahul         IT   900000.0                 5       Delhi
1   E102  Ananya         HR   600000.0                 4      Mumbai
2   E103    Amit    Finance   850000.0                 6   Bangalore
3   E104   Priya         IT  1200000.0                 8       Delhi
4   E105   Rohit      Sales   700000.0                 3        Pune
5   E106    Neha         HR        NaN                 5      Mumbai
6   E107   Karan    Finance   950000.0                 7   Bangalore
7   E108  Simran      Sales   650000.0                 2  Chandigarh
8   E109   Arjun         IT  1100000.0                 9   Hyderabad
9   E110   Sneha    Finance        NaN                 4       Delhi

In [31]:
df.groupby('department')['salary'].mean()

department
Finance    9.000000e+05
HR         6.000000e+05
IT         1.066667e+06
Sales      6.750000e+05
Name: salary, dtype: float64

In [32]:
df.groupby('department').agg({
    "salary": ["mean","max"]
})

                  salary
                    mean        max
department
Finance     9.000000e+05   950000.0
HR          6.000000e+05   600000.0
IT          1.066667e+06  1200000.0
Sales       6.750000e+05   700000.0

In [33]:
df.groupby('department')['salary'].max()

department
Finance     950000.0
HR          600000.0
IT         1200000.0
Sales       700000.0
Name: salary, dtype: float64

In [34]:
df.sort_values(by="salary", ascending=False).head(10)

  emp_id    name department     salary  experience_years        city
3   E104   Priya         IT  1200000.0                 8       Delhi
8   E109   Arjun         IT  1100000.0                 9   Hyderabad
6   E107   Karan    Finance   950000.0                 7   Bangalore
0   E101   Rahul         IT   900000.0                 5       Delhi
2   E103    Amit    Finance   850000.0                 6   Bangalore
4   E105   Rohit      Sales   700000.0                 3        Pune
7   E108  Simran      Sales   650000.0                 2  Chandigarh
1   E102  Ananya         HR   600000.0                 4      Mumbai
5   E106    Neha         HR        NaN                 5      Mumbai
9   E110   Sneha    Finance        NaN                 4       Delhi

In [35]:
df[(df['salary']> df['salary'].mean())]

  emp_id   name department     salary  experience_years       city
0   E101  Rahul         IT   900000.0                 5      Delhi
3   E104  Priya         IT  1200000.0                 8      Delhi
6   E107  Karan    Finance   950000.0                 7  Bangalore
8   E109  Arjun         IT  1100000.0                 9  Hyderabad

In [36]:
df[(df['experience_years']>5) & (df['salary']>900000)]

  emp_id   name department     salary  experience_years       city
3   E104  Priya         IT  1200000.0                 8      Delhi
6   E107  Karan    Finance   950000.0                 7  Bangalore
8   E109  Arjun         IT  1100000.0                 9  Hyderabad

In [37]:
pd.pivot_table(df, values="salary", index="department", aggfunc="mean")

                  salary
department
Finance     9.000000e+05
HR          6.000000e+05
IT          1.066667e+06
Sales       6.750000e+05

In [38]:
null_val = df['salary'].isnull()
null_val.sum()

np.int64(2)

In [39]:
df['salary'].fillna(df.groupby('department')['salary'].transform('mean'), inplace=True)

/var/folders/kf/46fvvcgx371d5df6s5n8qp_w0000gn/T/ipykernel_18812/140988588.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df.groupby('department')['salary'].transform('mean'), inplace=True)

In [40]:
df

  emp_id    name department     salary  experience_years        city
0   E101   Rahul         IT   900000.0                 5       Delhi
1   E102  Ananya         HR   600000.0                 4      Mumbai
2   E103    Amit    Finance   850000.0                 6   Bangalore
3   E104   Priya         IT  1200000.0                 8       Delhi
4   E105   Rohit      Sales   700000.0                 3        Pune
5   E106    Neha         HR   600000.0                 5      Mumbai
6   E107   Karan    Finance   950000.0                 7   Bangalore
7   E108  Simran      Sales   650000.0                 2  Chandigarh
8   E109   Arjun         IT  1100000.0                 9   Hyderabad
9   E110   Sneha    Finance   900000.0                 4       Delhi