employees.csv

Columns: name, department, salary

Department-wise average salary

Highest salary employee

Salary > 50000 waale log

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('employees.csv')
df

    name department  salary
0   Aman         IT   60000
1   Riya         HR   45000
2   Shiv         IT   75000
3   Neha    Finance   52000
4  Arjun         HR   48000

In [4]:
dep_salary = df.groupby('department')['salary'].mean()
dep_salary

department
Finance    52000.0
HR         46500.0
IT         67500.0
Name: salary, dtype: float64

In [5]:
highest_salary = df.loc[[df['salary'].idxmax()]]
highest_salary

   name department  salary
2  Shiv         IT   75000

In [6]:
list = df[df['salary']>50000]
list

   name department  salary
0  Aman         IT   60000
2  Shiv         IT   75000
3  Neha    Finance   52000