Weather dataset:

Columns: day, temperature

Max temp

Min temp

Average temp using NumPy

DataFrame me new column add karo: "Status"

temp > avg → "Hot"

else → "Cool"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('weather.csv')
df

   day  temperature
0  Mon           32
1  Tue           35
2  Wed           30
3  Thu           28
4  Fri           36
5  Sat           34
6  Sun           29

In [4]:
max_temp = df.loc[[df['temperature'].idxmax()]]
min_temp = df.loc[[df['temperature'].idxmin()]]

In [5]:
max_temp

   day  temperature
4  Fri           36

In [6]:
min_temp

   day  temperature
3  Thu           28

In [7]:
avg_temp = np.mean(df['temperature'])
print("Average Temperature:", avg_temp)

Average Temperature: 32.0

In [8]:
df["Status"] = df["temperature"].apply(lambda x: "Hot" if x > avg_temp else "Cool")
df

   day  temperature Status
0  Mon           32   Cool
1  Tue           35    Hot
2  Wed           30   Cool
3  Thu           28   Cool
4  Fri           36    Hot
5  Sat           34    Hot
6  Sun           29   Cool