Student attendance:

Columns: name, attendance_percentage

<75% waale students

Mean attendance

Top 3 attendance

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('attendance.csv')
data

    name  attendance_percentage
0   Aman                     82
1   Riya                     68
2   Shiv                     74
3   Neha                     90
4  Arjun                     60
5  Karan                     88

In [4]:
less_attendance = data[data['attendance_percentage']<75]
less_attendance

    name  attendance_percentage
1   Riya                     68
2   Shiv                     74
4  Arjun                     60

In [5]:
mean_att = data['attendance_percentage'].mean()
print('Attendance Average:', mean_att)

att_mean = np.array(data['attendance_percentage'])
np.mean(att_mean)

Attendance Average: 77.0

np.float64(77.0)

In [8]:
top3 = data.sort_values(by="attendance_percentage", ascending=False).head(3)
print("Top 3 Attendance:\n", top3)

Top 3 Attendance:
     name  attendance_percentage
3   Neha                     90
5  Karan                     88
0   Aman                     82