Movies dataset:

Columns: name, rating, year

Highest rated movie

Movies after 2020

Average rating using NumPy

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('movies.csv')
df

          name  rating  year
0    Inception     8.8  2010
1          KGF     8.4  2018
2          RRR     8.6  2022
3     Avatar 2     7.8  2022
4  Oppenheimer     9.0  2023
5       Pushpa     7.6  2021

In [3]:
highest_rated = df.loc[[df['rating'].idxmax()]]
highest_rated

          name  rating  year
4  Oppenheimer     9.0  2023

In [4]:
after_20 = df[df['year']>2020]
after_20

          name  rating  year
2          RRR     8.6  2022
3     Avatar 2     7.8  2022
4  Oppenheimer     9.0  2023
5       Pushpa     7.6  2021

In [5]:
avg_rating = np.mean(df['rating'])
print("Average rating:", avg_rating)

Average rating: 8.366666666666667