In [14]:
# Dataset:

# data = {
#     "Name": ["Ali", "Sara", "John", "Emma", "David"],
#     "Marks": [78, 92, 65, 88, 55],
#     "Attendance": [85, 95, 70, 90, 60]
# }

# Tasks:
# average marks
# topper name
# lowest scorer
# students above 80
# attendance below 75
# create bonus column
# final marks after bonus
# sort by final marks

In [15]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma", "David"],
    "Marks": [78, 92, 65, 88, 55],
    "Attendance": [85, 95, 70, 90, 60]
}
df = pd.DataFrame(data)

# average marks
df['Marks'].mean()

np.float64(75.6)

In [16]:
# topper name
df.sort_values('Marks', ascending=False).head(1)

   Name  Marks  Attendance
1  Sara     92          95

In [17]:
# lowest scorer
df.sort_values('Marks').head(1)

    Name  Marks  Attendance
4  David     55          60

In [18]:
# students above 80
df[df['Marks']>80]

   Name  Marks  Attendance
1  Sara     92          95
3  Emma     88          90

In [19]:
# attendance below 75
df[df['Attendance']<75]

    Name  Marks  Attendance
2   John     65          70
4  David     55          60

In [20]:
# create bonus column
df['Bonus'] = 5

In [21]:
# final marks after bonus
df['FinalMarks'] = df['Marks']+df['Bonus']

In [22]:
# sort by final marks
df.sort_values('FinalMarks', ascending=False)

    Name  Marks  Attendance  Bonus  FinalMarks
1   Sara     92          95      5          97
3   Emma     88          90      5          93
0    Ali     78          85      5          83
2   John     65          70      5          70
4  David     55          60      5          60

In [ ]:
# REAL-WORLD ANALYST THINKING TASK
# Imagine:
# You work in ed-tech company.

# Question:
# Why attendance important along with marks?
# Why average marks alone misleading ho sakta?
# Which students need intervention?
# Which chart would best show marks comparison?

# Think like analyst.
# Not coder.