In [6]:
# BONUS CHALLENGE 🔥

# Create DataFrame:

# Product | Price

# Then:
# add GST column
# create FinalPrice column
# filter products above ₹25000
# sort highest to lowest price

In [7]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "Price": [55000, 25000, 18000]
})

In [8]:
# add GST column
df['GST'] = df['Price']*0.18

In [9]:
# create FinalPrice column
df['FinalPrice'] = df['Price'] + df['GST']
df

  Product  Price     GST  FinalPrice
0  Laptop  55000  9900.0     64900.0
1   Phone  25000  4500.0     29500.0
2  Tablet  18000  3240.0     21240.0

In [ ]:
# filter products above ₹25000
df[df['FinalPrice']>25000]

  Product  Price     GST  FinalPrice
0  Laptop  55000  9900.0     64900.0
1   Phone  25000  4500.0     29500.0

In [11]:
# sort highest to lowest price
df.sort_values('FinalPrice', ascending=False)

  Product  Price     GST  FinalPrice
0  Laptop  55000  9900.0     64900.0
1   Phone  25000  4500.0     29500.0
2  Tablet  18000  3240.0     21240.0

In [ ]:
# TODAY’S INTERVIEW QUESTIONS
# Prepare answers:

# 1.
# What is Pandas?

# 2.
# Difference between Series and DataFrame?

# 3.
# Why Pandas important for Data Analysts?

# 4.
# What does .head() do?

# 5.
# What does .info() show?

In [ ]:
# 1. What is Pandas?

# Pandas ek Python library hai jo data analysis aur data manipulation ke liye use hoti hai.

# Ye tabular data handle karne me help karti hai like Excel tables or SQL data.

# Practical Example:
# import pandas as pd

# data = {
#     "Name": ["Ali", "Sara"],
#     "Marks": [85, 92]
# }

# df = pd.DataFrame(data)

# print(df)
# Interview Line:

# “Pandas is a powerful Python library used for cleaning, analyzing, and manipulating structured data.”

# 2. Difference between Series and DataFrame?
# Series	DataFrame
# One-dimensional	Two-dimensional
# Single column data	Multiple columns data
# Like a list with index	Like an Excel table
# Practical Example:
# import pandas as pd

# # Series
# s = pd.Series([10, 20, 30])

# # DataFrame
# df = pd.DataFrame({
#     "Marks": [80, 90],
#     "Age": [20, 21]
# })
# Interview Line:

# “Series single-column data structure hota hai, while DataFrame multiple rows and columns handle karta hai.”

# 3. Why is Pandas important for Data Analysts?

# Pandas important hai because:

# Data cleaning easy ho jati hai
# Missing values handle kar sakte hain
# Filtering, sorting, grouping easy hota hai
# CSV/Excel files easily read kar sakte hain
# Practical Example:
# df = pd.read_csv("data.csv")
# Interview Line:

# “Pandas helps Data Analysts efficiently clean, transform, and analyze large datasets.”

# 4. What does .head() do?

# .head() dataset ki starting rows show karta hai.

# Default:
# First 5 rows.

# Practical Example:
# print(df.head())
# Interview Line:

# “.head() quickly preview karne ke liye use hota hai taaki dataset structure samajh aaye.”

# 5. What does .info() show?

# .info() dataset ka summary deta hai:

# Number of rows
# Column names
# Data types
# Missing values
# Practical Example:
# print(df.info())
# Interview Line:

# “.info() dataset ka structural overview provide karta hai including columns, datatypes, and null values.”