In [2]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Marks": [78, 92, 65, 88]
}

df = pd.DataFrame(data)

In [ ]:
# Q8
# Add new column:
# Bonus = 5

df['Bonus'] = 5

   Name  Marks  Bonus
0   Ali     78      5
1  Sara     92      5
2  John     65      5
3  Emma     88      5

In [5]:
# Q9
# Create:
# FinalMarks = Marks + Bonus

df['FinalMarks'] = df['Marks'] + df['Bonus']
df

   Name  Marks  Bonus  FinalMarks
0   Ali     78      5          83
1  Sara     92      5          97
2  John     65      5          70
3  Emma     88      5          93