In [56]:
# Q1
# Create DataFrame:

# Name | Age
# A    | 21
# B    | 22
# C    | 20

In [57]:
import pandas as pd

In [58]:
Students ={
    "Name": ['A', 'B', 'C'],
    "Age": [21, 22, 20]
}

df = pd.DataFrame(Students)
df

  Name  Age
0    A   21
1    B   22
2    C   20

In [59]:
# Q2
# Print:
# first 2 rows
# last row
# shape
# columns

In [60]:
print(df.head(2))

  Name  Age
0    A   21
1    B   22

In [61]:
df.tail(1)

  Name  Age
2    C   20

In [62]:
df.shape

(3, 2)

In [63]:
df.columns

Index(['Name', 'Age'], dtype='object')